import React, { useState, useEffect } from "react";
import { Expense, AuditLog } from "@/entities/all";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import MaterialIcon from "@/components/ui/MaterialIcon";
import { toast } from "sonner";
import { format } from "date-fns";
import { EXPENSE_CATEGORIES, getCategoryMeta } from "@/lib/expenseCategories";

export default function ExpenseForm({ expense, franchiseId, currentUser, onSave, onCancel }) {
  const isEditing = !!expense;
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [description, setDescription] = useState("");
  const [amount, setAmount] = useState("");
  const [expenseDate, setExpenseDate] = useState(format(new Date(), "yyyy-MM-dd"));
  const [category, setCategory] = useState("outros");
  const [supplier, setSupplier] = useState("");

  useEffect(() => {
    if (expense) {
      setDescription(expense.description || "");
      setAmount(expense.amount || "");
      setExpenseDate(expense.expense_date || format(new Date(), "yyyy-MM-dd"));
      setCategory(expense.category || "outros");
      setSupplier(expense.supplier || "");
    }
  }, [expense]);

  const isAutoGenerated = expense?.source && expense.source !== "manual";
  const categoryMeta = getCategoryMeta(category);

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!description.trim()) {
      toast.error("Informe a descrição da despesa.");
      return;
    }

    const parsedAmount = parseFloat(amount);
    if (!parsedAmount || parsedAmount <= 0) {
      toast.error("Informe um valor maior que zero.");
      return;
    }

    setIsSubmitting(true);
    try {
      const data = {
        franchise_id: franchiseId,
        description: description.trim(),
        amount: parsedAmount,
        expense_date: expenseDate,
        category,
        supplier: supplier.trim() || null,
        created_by: currentUser?.id || null,
      };

      // Em CREATE, força source='manual' (despesa lançada manualmente).
      // Em UPDATE, NÃO sobrescreve source (mantém auto-geradas como purchase_order/marketing_payment).
      if (!isEditing) {
        data.source = "manual";
      }

      let entityId;
      if (isEditing) {
        await Expense.update(expense.id, data);
        entityId = expense.id;
        toast.success("Despesa atualizada!");
      } else {
        const created = await Expense.create(data);
        entityId = created.id;
        toast.success("Despesa lançada!");
      }

      // Audit log enriquecido com category + supplier
      try {
        await AuditLog.create({
          user_id: currentUser?.id || null,
          user_name: currentUser?.full_name || currentUser?.email || "Desconhecido",
          franchise_id: franchiseId,
          action: isEditing ? "update" : "create",
          entity_type: "expense",
          entity_id: entityId,
          details: {
            description: description.trim(),
            amount: parsedAmount,
            expense_date: expenseDate,
            category,
            supplier: supplier.trim() || null,
          },
        });
      } catch (auditErr) {
        console.warn("Audit log failed:", auditErr);
      }

      onSave();
    } catch (error) {
      console.error("Erro ao salvar despesa:", error);
      toast.error("Erro ao salvar despesa. Tente novamente.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {/* Aviso quando editando despesa auto-gerada (PO/marketing/ASAAS) */}
      {isAutoGenerated && (
        <div className="flex items-start gap-2 p-3 rounded-xl bg-[#fffbeb] border border-[#fde68a] text-xs text-[#775a19]">
          <MaterialIcon icon="info" size={16} className="shrink-0 mt-0.5" />
          <p>
            Esta despesa foi gerada automaticamente
            {expense.source === "purchase_order" && " ao receber pedido de reposição"}
            {expense.source === "marketing_payment" && " ao confirmar pagamento de marketing"}
            {expense.source === "external_purchase" && " ao lançar compra externa"}
            . Você pode editar valor e descrição, mas evite mudar a categoria.
          </p>
        </div>
      )}

      {/* Categoria — primeiro campo (decisão visual + setup mental) */}
      <div className="space-y-2">
        <Label htmlFor="expense-category" className="text-sm font-medium text-[#1b1c1d]">
          Categoria
        </Label>
        <Select value={category} onValueChange={setCategory}>
          <SelectTrigger id="expense-category" className="bg-[#e9e8e9]/50">
            <SelectValue>
              <span className="flex items-center gap-2">
                <MaterialIcon icon={categoryMeta.icon} size={16} style={{ color: categoryMeta.color }} />
                <span>{categoryMeta.label}</span>
              </span>
            </SelectValue>
          </SelectTrigger>
          <SelectContent>
            {EXPENSE_CATEGORIES.map((c) => (
              <SelectItem key={c.value} value={c.value}>
                <span className="flex items-center gap-2">
                  <MaterialIcon icon={c.icon} size={16} style={{ color: c.color }} />
                  <span className="font-medium">{c.label}</span>
                </span>
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        {categoryMeta.help && (
          <p className="text-[11px] text-[#4a3d3d]/70 leading-snug">{categoryMeta.help}</p>
        )}
      </div>

      {/* Descrição */}
      <div className="space-y-2">
        <Label htmlFor="expense-description" className="text-sm font-medium text-[#1b1c1d]">
          Descrição
        </Label>
        <Input
          id="expense-description"
          placeholder="Ex: Conta de luz CPFL, Frete moto, Salário ajudante..."
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          className="bg-[#e9e8e9]/50"
          autoComplete="off"
        />
      </div>

      {/* Fornecedor (opcional) */}
      <div className="space-y-2">
        <Label htmlFor="expense-supplier" className="text-sm font-medium text-[#1b1c1d]">
          Fornecedor <span className="text-[11px] text-[#4a3d3d]/60 font-normal">(opcional)</span>
        </Label>
        <Input
          id="expense-supplier"
          placeholder="Ex: CPFL, Mercado X, Distribuidora Y..."
          value={supplier}
          onChange={(e) => setSupplier(e.target.value)}
          className="bg-[#e9e8e9]/50"
          autoComplete="off"
          maxLength={120}
        />
      </div>

      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-2">
          <Label htmlFor="expense-amount" className="text-sm font-medium text-[#1b1c1d]">
            Valor (R$)
          </Label>
          <Input
            id="expense-amount"
            type="number"
            min={0.01}
            step={0.01}
            placeholder="0,00"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            className="bg-[#e9e8e9]/50 text-right font-mono-numbers"
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="expense-date" className="text-sm font-medium text-[#1b1c1d]">
            Data
          </Label>
          <Input
            id="expense-date"
            type="date"
            value={expenseDate}
            onChange={(e) => setExpenseDate(e.target.value)}
            className="bg-[#e9e8e9]/50"
          />
        </div>
      </div>

      <div className="flex gap-3 pt-2">
        <Button
          type="button"
          variant="outline"
          onClick={onCancel}
          className="flex-1"
          disabled={isSubmitting}
        >
          Cancelar
        </Button>
        <Button
          type="submit"
          disabled={isSubmitting}
          className="flex-1 bg-[#b91c1c] hover:bg-[#991b1b] text-white"
        >
          {isSubmitting ? (
            <>
              <MaterialIcon icon="progress_activity" size={16} className="animate-spin mr-2" />
              Salvando...
            </>
          ) : isEditing ? (
            "Atualizar"
          ) : (
            "Lançar despesa"
          )}
        </Button>
      </div>
    </form>
  );
}
